_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.10
            "8":
                - 5
            "12": 0.19.10
            "13": linux-x86_64
actor_lr:
    value: 0.0002
batch_size:
    value: 128
buffer_capacity:
    value: 1000000
critic_lr:
    value: 0.002
env_name:
    value: simple_tag_v3
episode_length:
    value: 500
episode_num:
    value: 5
gamma:
    value: 0.99
learn_interval:
    value: 10
random_steps:
    value: 500
render_mode:
    value: None
size_win:
    value: 200
tau:
    value: 0.001
visdom:
    value: false
